In [16]:
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.feature_extraction.text import CountVectorizer

In [17]:
vectorizer = CountVectorizer()
docs = np.array(['sunshine state enjoy sunshine',
                 'brown fox jump high, brown fox run',
                 'sunshine state fox run fast'])

In [18]:
bag = vectorizer.fit_transform(docs)
print(bag.toarray())

[[0 1 0 0 0 0 0 1 2]
 [2 0 0 2 1 1 1 0 0]
 [0 0 1 1 0 0 1 1 1]]


In [19]:

docs = np.array(['sunshine state enjoy sunshine',
                 'sunshine state fox run fast'])
standardData = docs.reshape(1,-1)

In [20]:
X = CountVectorizer().fit_transform(docs).toarray()
print(X)

[[1 0 0 0 1 2]
 [0 1 1 1 1 1]]


In [29]:

cos_sim = cosine_similarity([X[0, :], X[1, :]])
print('Cosine Similarity 1 and Document 3:\n',cos_sim[0,1])

Cosine Similarity 1 and Document 3:
 0.5477225575051662
